# Final Dataset Construction

This notebook combines all engineered features produced during the data preparation phase.

Sources:
- listings_features.csv
- review_features.csv

The resulting dataset will be used for machine learning models such as Decision Trees and Random Forests.

In [33]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent

print("Project root:", PROJECT_ROOT)

Project root: /Users/santiagotawata/Desktop/airbnb-rome-analysis

In [34]:
listings_features = pd.read_csv(
    "../data/listings_features.csv"
)

review_features = pd.read_csv(
    "../data/review_features.csv"
)

## Inspect Input Datasets

In [35]:
print(listings_features.shape)
print(review_features.shape)

(34324, 58)
(32827, 4)

In [36]:
listings_features.head()

,id,price,latitude,longitude,property_type,room_type,accommodates,bedrooms,beds,bathrooms,...,neighbourhood_cleansed_VII San Giovanni/Cinecittà,neighbourhood_cleansed_VIII Appia Antica,neighbourhood_cleansed_X Ostia/Acilia,neighbourhood_cleansed_XI Arvalia/Portuense,neighbourhood_cleansed_XII Monte Verde,neighbourhood_cleansed_XIII Aurelia,neighbourhood_cleansed_XIV Monte Mario,neighbourhood_cleansed_XV Cassia/Flaminia,distance_to_colosseum,location_cluster
0,2737,59.52,41.87136,12.48215,Private Room,Private room,1,1.0,1.0,1.5,...,False,True,False,False,False,False,False,False,2.252726,2.0
1,12398,117.13,41.92582,12.46928,Apartment,Entire home/apt,3,2.0,3.0,1.0,...,False,False,False,False,False,False,False,False,4.389669,0.0
2,19965,160.60,41.90823,12.45293,Apartment,Entire home/apt,5,2.0,3.0,1.0,...,False,False,False,False,False,False,False,False,3.824847,0.0
3,20534,243.67,41.88992,12.46823,Entire Home,Entire home/apt,4,1.0,3.0,1.0,...,False,False,False,False,False,False,False,False,1.989591,2.0
4,20587,302.50,41.88992,12.46823,Entire Home,Entire home/apt,4,2.0,4.0,1.0,...,False,False,False,False,False,False,False,False,1.989591,2.0

In [37]:
review_features.head()

   listing_id  review_count  avg_review_length latest_review_date
0        2737             5          51.800000         2015-05-08
1       11834           302          74.165563         2026-06-07
2       12398            85          84.658824         2025-08-01
3       19965           195          44.953846         2026-06-13
4       20534            50          60.200000         2022-11-22

In [38]:
## Verify Merge Key

In [39]:
print("id" in listings_features.columns)
print("listing_id" in review_features.columns)

True
True

## Merge Listings and Review Features

Review-based variables are merged into the listings dataset using the listing identifier.

A left join is used to preserve all listings.

In [40]:
print(review_features.columns.tolist())

['listing_id', 'review_count', 'avg_review_length', 'latest_review_date']

In [41]:
final_df = listings_features.merge(
    review_features,
    left_on="id",
    right_on="listing_id",
    how="left"
)

#deletion of duplicate key
final_df.drop(
    columns=["listing_id"],
    inplace=True
)

## Handle Missing Review Features

Listings without reviews do not appear in the reviews dataset.

Missing review-derived variables are replaced with zero.

In [42]:
final_df["review_count"] = (
    final_df["review_count"]
    .fillna(0)
)

final_df["avg_review_length"] = (
    final_df["avg_review_length"]
    .fillna(0)
)

In [43]:
final_df.columns.tolist()

['id',
 'price',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bedrooms',
 'beds',
 'bathrooms',
 'host_is_superhost',
 'host_response_rate',
 'host_acceptance_rate',
 'review_scores_rating',
 'review_scores_cleanliness',
 'review_scores_location',
 'review_scores_value',
 'number_of_reviews',
 'reviews_per_month',
 'minimum_nights',
 'maximum_nights',
 'instant_bookable',
 'beds_per_guest',
 'bathrooms_per_guest',
 'amenities_count',
 'has_wifi',
 'has_air_conditioning',
 'has_kitchen',
 'has_washer',
 'has_dryer',
 'has_parking',
 'has_elevator',
 'has_tv',
 'has_workspace',
 'professional_host',
 'review_quality_index',
 'listing_age_days',
 'review_recency_days',
 'review_intensity',
 'occupancy_rate',
 'demand_proxy',
 'neighbourhood_cleansed_I Centro Storico',
 'neighbourhood_cleansed_II Parioli/Nomentano',
 'neighbourhood_cleansed_III Monte Sacro',
 'neighbourhood_cleansed_IV Tiburtina',
 'neighbourhood_cleansed_IX Eur',
 'neighbourhood_cleansed_V Prenestino/Centocelle',
 'neighbourhood_cleansed_VI Roma delle Torri',
 'neighbourhood_cleansed_VII San Giovanni/Cinecittà',
 'neighbourhood_cleansed_VIII Appia Antica',
 'neighbourhood_cleansed_X Ostia/Acilia',
 'neighbourhood_cleansed_XI Arvalia/Portuense',
 'neighbourhood_cleansed_XII Monte Verde',
 'neighbourhood_cleansed_XIII Aurelia',
 'neighbourhood_cleansed_XIV Monte Mario',
 'neighbourhood_cleansed_XV Cassia/Flaminia',
 'distance_to_colosseum',
 'location_cluster',
 'review_count',
 'avg_review_length',
 'latest_review_date']

In [44]:
final_df["latest_review_date"] = pd.to_datetime(
    final_df["latest_review_date"]
)

`days_since_latest_review`

In [45]:
reference_date = final_df["latest_review_date"].max()

final_df["days_since_latest_review"] = (
    reference_date - final_df["latest_review_date"]
).dt.days

Full fill empty dates

In [46]:
final_df["days_since_latest_review"] = (
    final_df["days_since_latest_review"]
    .fillna(9999)
)

## Final Dataset Validation

In [47]:
print(final_df.shape)

(34324, 62)

In [48]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34324 entries, 0 to 34323
Data columns (total 62 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   id                                                 34324 non-null  int64
 1   price                                              34324 non-null  float64
 2   latitude                                           34324 non-null  float64
 3   longitude                                          34324 non-null  float64
 4   property_type                                      34324 non-null  object
 5   room_type                                          34324 non-null  object
 6   accommodates                                       34324 non-null  int64
 7   bedrooms                                           34324 non-null  float64
 8   beds                                               34324 non-null  float64
 9   bathrooms                                          34324 non-null  float64
 10  host_is_superhost                                  34324 non-null  int64
 11  host_response_rate                                 0 non-null      float64
 12  host_acceptance_rate                               0 non-null      float64
 13  review_scores_rating                               34324 non-null  float64
 14  review_scores_cleanliness                          34324 non-null  float64
 15  review_scores_location                             34324 non-null  float64
 16  review_scores_value                                34324 non-null  float64
 17  number_of_reviews                                  34324 non-null  int64
 18  reviews_per_month                                  34324 non-null  float64
 19  minimum_nights                                     34311 non-null  float64
 20  maximum_nights                                     34311 non-null  float64
 21  instant_bookable                                   34324 non-null  object
 22  beds_per_guest                                     34324 non-null  float64
 23  bathrooms_per_guest                                34324 non-null  float64
 24  amenities_count                                    34324 non-null  int64
 25  has_wifi                                           34324 non-null  int64
 26  has_air_conditioning                               34324 non-null  int64
 27  has_kitchen                                        34324 non-null  int64
 28  has_washer                                         34324 non-null  int64
 29  has_dryer                                          34324 non-null  int64
 30  has_parking                                        34324 non-null  int64
 31  has_elevator                                       34324 non-null  int64
 32  has_tv                                             34324 non-null  int64
 33  has_workspace                                      34324 non-null  int64
 34  professional_host                                  34324 non-null  int64
 35  review_quality_index                               34324 non-null  float64
 36  listing_age_days                                   34324 non-null  float64
 37  review_recency_days                                34324 non-null  float64
 38  review_intensity                                   34324 non-null  float64
 39  occupancy_rate                                     34324 non-null  float64
 40  demand_proxy                                       34324 non-null  float64
 41  neighbourhood_cleansed_I Centro Storico            34324 non-null  bool
 42  neighbourhood_cleansed_II Parioli/Nomentano        34324 non-null  bool
 43  neighbourhood_cleansed_III Monte Sacro             34324 non-null  bool
 44  neighbourhood_cleansed_IV Tiburtina                34324 non-null  bool
 45  neighbourhood_cleansed_IX Eur                      34324 non-null  bool
 46  neighbourhood_cleansed_V Prenestino/Centocelle     34324 non-null  bool
 47  neighbourhood_cleansed_VI Roma delle Torri         34324 non-null  bool
 48  neighbourhood_cleansed_VII San Giovanni/Cinecittà  34324 non-null  bool
 49  neighbourhood_cleansed_VIII Appia Antica           34324 non-null  bool
 50  neighbourhood_cleansed_X Ostia/Acilia              34324 non-null  bool
 51  neighbourhood_cleansed_XI Arvalia/Portuense        34324 non-null  bool
 52  neighbourhood_cleansed_XII Monte Verde             34324 non-null  bool
 53  neighbourhood_cleansed_XIII Aurelia                34324 non-null  bool
 54  neighbourhood_cleansed_XIV Monte Mario             34324 non-null  bool
 55  neighbourhood_cleansed_XV Cassia/Flaminia          34324 non-null  bool
 56  distance_to_colosseum                              34324 non-null  float64
 57  location_cluster                                   30987 non-null  float64
 58  review_count                                       34324 non-null  float64
 59  avg_review_length                                  34324 non-null  float64
 60  latest_review_date                                 30571 non-null  datetime64[ns]
 61  days_since_latest_review                           34324 non-null  float64
dtypes: bool(15), datetime64[ns](1), float64(28), int64(15), object(3)
memory usage: 12.8+ MB

In [49]:
final_df.isnull().sum().sort_values(
    ascending=False
).head(20)

host_response_rate                                   34324
host_acceptance_rate                                 34324
latest_review_date                                    3753
location_cluster                                      3337
maximum_nights                                          13
minimum_nights                                          13
neighbourhood_cleansed_IX Eur                            0
neighbourhood_cleansed_IV Tiburtina                      0
neighbourhood_cleansed_III Monte Sacro                   0
neighbourhood_cleansed_II Parioli/Nomentano              0
id                                                       0
neighbourhood_cleansed_I Centro Storico                  0
occupancy_rate                                           0
review_intensity                                         0
review_recency_days                                      0
listing_age_days                                         0
review_quality_index                                     0
demand_proxy                                             0
neighbourhood_cleansed_VII San Giovanni/Cinecittà        0
neighbourhood_cleansed_V Prenestino/Centocelle           0
dtype: int64

## Export Final Dataset

The final modeling dataset is saved and will be used for machine learning models.

In [50]:
final_df.to_csv(
    "../data/final_dataset.csv",
    index=False
)

print("final_dataset.csv saved")

final_dataset.csv saved

In [51]:
final_df.shape

(34324, 62)

In [52]:
final_df.columns.tolist()

['id',
 'price',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bedrooms',
 'beds',
 'bathrooms',
 'host_is_superhost',
 'host_response_rate',
 'host_acceptance_rate',
 'review_scores_rating',
 'review_scores_cleanliness',
 'review_scores_location',
 'review_scores_value',
 'number_of_reviews',
 'reviews_per_month',
 'minimum_nights',
 'maximum_nights',
 'instant_bookable',
 'beds_per_guest',
 'bathrooms_per_guest',
 'amenities_count',
 'has_wifi',
 'has_air_conditioning',
 'has_kitchen',
 'has_washer',
 'has_dryer',
 'has_parking',
 'has_elevator',
 'has_tv',
 'has_workspace',
 'professional_host',
 'review_quality_index',
 'listing_age_days',
 'review_recency_days',
 'review_intensity',
 'occupancy_rate',
 'demand_proxy',
 'neighbourhood_cleansed_I Centro Storico',
 'neighbourhood_cleansed_II Parioli/Nomentano',
 'neighbourhood_cleansed_III Monte Sacro',
 'neighbourhood_cleansed_IV Tiburtina',
 'neighbourhood_cleansed_IX Eur',
 'neighbourhood_cleansed_V Prenestino/Centocelle',
 'neighbourhood_cleansed_VI Roma delle Torri',
 'neighbourhood_cleansed_VII San Giovanni/Cinecittà',
 'neighbourhood_cleansed_VIII Appia Antica',
 'neighbourhood_cleansed_X Ostia/Acilia',
 'neighbourhood_cleansed_XI Arvalia/Portuense',
 'neighbourhood_cleansed_XII Monte Verde',
 'neighbourhood_cleansed_XIII Aurelia',
 'neighbourhood_cleansed_XIV Monte Mario',
 'neighbourhood_cleansed_XV Cassia/Flaminia',
 'distance_to_colosseum',
 'location_cluster',
 'review_count',
 'avg_review_length',
 'latest_review_date',
 'days_since_latest_review']

## Data Preprocessing

Machine learning algorithms require numerical inputs.

Categorical variables are encoded and date variables are transformed into numerical representations.

dsjnfkcjds,